# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # CPU microcode
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";

  # GPU Driver
  hardware.opengl.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ pkgs.asus-wmi-sensors ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/30ec9bb8-cdfd-4ad3-90ae-c179ea0dc8f9";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2182-F9AE";
      fsType = "vfat";
    };

  # swapDevices = [ ];
}